version: 2

# Build documentation in the docs/ directory with MkDocs
mkdocs:
  configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF
formats: all

python:
  version: 3.8
  install:
    - requirements: .readthedocs.reqs.txt
    - path: .
