site_name: testing-shit
theme:
  name: "material"
  palette:
    scheme: slate
    primary: teal

nav:
  - Home: index.md
  - About: about.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
