site_name: AtroArgs
theme:
  name: "material"
  palette:
    scheme: slate
    primary: teal
  features:
    - search.suggest
plugins:
  - search:
      lang: en
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            heading_level: 2
nav:
  - Home: index.md
  - References: references.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
